baseURL = "https://rladies-dev.netlify.app/"
languageCode = "en"
title = "R-Ladies Global"
theme = "hugo-rladies"
publishDir = "build"
ignoreFiles = ["\\.Rmd$", "_cache$", "\\.DS_Store", "_files$", 
  "content/post/\\*/index\\*\\.html", "_cache$", "README"]
  
defaultContentLanguage = "en"
pygmentsUseClasses = true
enableGitInfo = true
enableRobotsTXT= true

#[outputs]
#  home = ["HTML", "RSS", "JSON"]