baseURL = "/"
languageCode = "en-us"
title = "R-Ladies Global"
theme = "hugo-initio-athanasiamo"
publishDir = "public"
ignoreFiles = ["\\.Rmd$", "_cache$", ".DS_Store", "_files$", "index\\.html", "_cache$", "README"]


[languages.en]
languageName = "English"
description = "R-Ladies is a world-wide organization to promote gender diversity in the R community"
weight = 1

[languages.fr]
languageName = "Français"
weight = 2
#description = ""

[languages.es]
languageName = "Español"
weight = 3
#description = ""

[params]
    name = "R-Ladies Global"
    email = "info@rladies.org"
    coc = "/coc/"
    year = 2013
    avatar = "images/logo.png"
    #banner = "images/header.jpg"
    favicon = "images/favicon.png"
    imgclass = "rounded"
    DateForm = "January 2, 2006"
    customCSS = ["css/rladies.css"] #apply custom css, must be in assets/  

    showSubheader = false
    showServices = true
    showRecentWorks = false
    showDownload = false
    showClients = true

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

# Nav menu ----
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
[[menu.main]]
    name = "About"
    url = "#"
    identifier = "about-us"
    weight = 2
[[menu.main]]
    name = "Mission"
    url = "/about-us/mission/"
    weight = 1
    parent = "about-us"
[[menu.main]]
    name = "Get involved"
    url = "/about-us/involved/"
    weight = 2
    parent = "about-us"
[[menu.main]]
    name = "Meet the global team"
    url = "/about-us/global-team/"
    weight = 3
    parent = "about-us"
[[menu.main]]
    name = "History"
    url = "/about-us/history/"
    weight = 4
    parent = "about-us"
    
[[menu.main]]
    name = "Activities"
    url = "#"
    identifier = "activities"
    weight = 3
[[menu.main]]
    name = "Events"
    url = "/activities/events/"
    weight = 1
    parent = "activities"
[[menu.main]]
    name = "R-Ladies Directory"
    url = "/activities/directory/"
    weight = 2
    parent = "activities"
[[menu.main]]
    name = "Mentoring Program"
    url = "/activities/mentoring/"
    weight = 3
    parent = "activities"
[[menu.main]]
    name = "Rotating Twitter Curator"
    url = "/activities/rocur/"
    weight = 4
    parent = "activities"
[[menu.main]]
    name = "Abstract review"
    url = "/activities/review/"
    weight = 5
    parent = "activities"
[[menu.main]]
    name = "International Women's Day Campaigns"
    url = "/activities/iwd/"
    weight = 6
    parent = "activities"
[[menu.main]]
    name = "Community Slack"
    url = "/activities/community-slack/"
    weight = 7
    parent = "activities"
[[menu.main]]
    name = "Global dashboard"
    url = "https://benubah.github.io/r-community-explorer/rladies.html"
    weight = 8
    parent = "activities"
    
[[menu.main]]
    name = "Blog"
    url = "https://blog.rladies.org/"
    weight = 4

# Analytics ----
[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"


# Socials ----
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/RLadiesGlobal"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/rladiesglobal"
    icon = "fab fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "github"
	url = "https://github.com/rladies"
    icon = "fab fa-github-square"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
  title = "meetup"
	url = "https://www.meetup.com/pro/rladies/"
    footer = true
    sharethis = true
    icon = "fab fa-meetup"
    network = ""
[[params.social]]
  title = "youtube"
	url = "https://www.youtube.com/channel/UCDgj5-mFohWZ5irWSFMFcng"
    footer = true
    sharethis = true
    icon = "fab fa-youtube"
    network = ""
    
[[params.twitter]]
  title = "We are R-Ladies"
	url = "https://twitter.com/WeAreRLadies"
    footer = true
    sharethis = false
    network = ""
[[params.twitter]]
  title = "IWD R-Ladies"
	url = "https://twitter.com/rladies_iwd"
    footer = true
    sharethis = false
    network = ""
