name: New chapter
description: Add a new R-Ladies chapter
title: "[chapter-new]: "
labels: ["chapter", "new"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting in a new chapter.
  - type: input
    id: Country
    attributes:
      label: Chapter country
      description: Be diligent in spelling.
      placeholder: ex. India
    validations:
      required: true
  - type: input
    id: StateRegion
    attributes:
      label: Chapter state/region
      description: Be diligent in spelling.
      placeholder: ex. Eastern
    validations:
      required: false
  - type: input
    id: City
    attributes:
      label: Chapter city
      description: All chapters must be in a city. Be diligent in spelling.
      placeholder: ex. New Delhi
    validations:
      required: true
  - type: group
    id: social_media
    attributes:
      label: Social media
    children:
      - type: input
        id: meetup
        attributes:
          label: Meetup group name
          placeholder: rladies/city
          description: Please only create this issue once meetup is initiated, this URL is important for other website logistics.
        validations:
          required: true
      - type: input
        id: twitter
        attributes:
          label: Twitter handle
          placeholder: @rladies_city
      - type: input
        id: email
        attributes:
          label: Email address
          placeholder: r-ladies@domain.com
      - type: input
        id: facebook
        attributes:
          label: Facebook page URL
  - type: group
    id: organizers
    attributes:
      label: Organizers
    children:
      - type: input
        id: current
        attributes:
          label: Current organizers
          description: Please provide a comma-separated list of current organizers, without quotes.
        validations:
          required: true
