on:
  pull_request:
    branches:
      - main
      - master

name: Build site and preview

jobs:
  build:
    runs-on: macOS-latest
    name: Build site and preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'
          extended: true

      - name: Build
        env: 
          DIRECTORY_PAT: ${{ secrets.DIRECTORY_PAT }}
        run: hugo --minify

      - name: Install netlify
        run: npm install netlify-cli -g
        
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy
