# on:
#   push:
#     branches:
#       - main
#       - master
# 
# name: build_site
# 
# jobs:
#   build:
#     runs-on: macOS-latest
#     env:
#       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
#     steps:
#     
#       - name: Deploy to Netlify
#         # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
#         env:
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#         run: |
#           npm install netlify-cli -g
#           netlify deploy --prod
