name: Build site and deploy

on:
  pull_request:
    branches:
      - main
      - fork_merge
  push:
    branches: 
      - main
  schedule:
  - cron: "0 */12 * * *"

jobs:
  check:
    runs-on: macOS-latest
    name: Check modified jsons
    outputs:
      run_job: ${{ steps.check_files.outputs.run_validation }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
        
      - name: Find modified json data
        id: check_files
        run: |
          echo "step 1"
          echo $(git diff --name-only HEAD^ HEAD) > tmp
          cat tmp
          grep ^data tmp > tmp2 
          echo "step 2"
          grep json$ tmp2 > tmp 
          echo "step 3"
          if [[ -s tmp ]]; then 
            echo "::set-output name=run_validation::false"
          else
            echo "::set-output name=run_validation::true"
          fi
          
  validate:
    runs-on: macOS-latest
    name: Validate jsons
    needs: check
    if: needs.check.outputs.run_validation == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        
      - name: Run Renv
        uses: r-lib/actions/setup-renv@v1
        with:
          cache-version: 2
      
      - name: Validate jsons
        run: Rscript scripts/validate_jsons.R
        
  meetup:
    runs-on: macOS-latest
    name: Update meetup data
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main' && github.repository == 'rladies/website'
    env: 
      MEETUPR_PWD: ${{ secrets.MEETUPR_PWD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        
      - name: Run Renv
        uses: r-lib/actions/setup-renv@v1
        with:
          cache-version: 2
          
      - name: Meetup authentication
        run:  Rscript scripts/meetup_auth.R
        
      - name: Update chapter data
        run:  Rscript scripts/get_chapters.R
        
      - name: Update event data
        run:  Rscript scripts/get_events.R
        
      - name: Commit data	
        run: |	
          git config --local user.email "actions@github.com"	
          git config --local user.name "GitHub Actions"	
          git add data/events.json data/chapters.json data/events_updated.json	
          git commit -m 'Update meetup data' || echo "No meetup data to commit"	
        
  build:
    runs-on: macOS-latest
    name: Build and publish to Netlify
    if: ${{ always() && github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository}}
    needs: [validate, meetup]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.1'
          extended: true
      
      - name: Install netlify
        run: npm install netlify-cli -g
               
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        
      - name: Run Renv
        uses: r-lib/actions/setup-renv@v1
        with:
          cache-version: 2
              
      - name: Populate untranslated pages
        run: Rscript scripts/missing_translations.R
        
      - name: Site Data - Update Global Team
        run: Rscript scripts/get_global_team.R
        
      - name: Site data - Get directory data
        uses: actions/checkout@v2
        with:
          repository: rladies/directory
          ssh-key: ${{ secrets.DIRECTORY_DEPLOY_SECRET}}
          path: tmp
      
      - name: Site data - Get blogs list
        uses: actions/checkout@v2
        with:
          repository: rladies/awesome-rladies-blogs
          ssh-key: ${{ secrets.RLADIES_BLOGS_KEY}}
          path: rblogs
          
      - name: Site data - cloned repos
        run: |
          mv rblogs/blogs data/rblogs
          mv tmp/data/json data/directory
          mv tmp/data/img static/images/directory
          rm -rf tmp rblogs

      - name: Build
        run: hugo --enableGitInfo
        
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          if [ github.event_name == 'pull_request' ]; then
            echo "Deploying netlify preview"
            netlify deploy
          else
            echo "Deploying netlify production"
            netlify deploy --prod
          fi
        shell: sh
        
      - name: Commit data	
        run: |	
          git config --local user.email "actions@github.com"	
          git config --local user.name "GitHub Actions"	
          git add data/global_team.json
          git commit -m 'Update global team' || echo "No global team changes to commit"	
          git push origin || echo "Nothing to push"
