name: Build site and deploy

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches: 
      - master
  schedule:
  - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: macOS-latest
    name: Build and publish to Netlify
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
               
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
              
      - name: Install R dependencies
        run: |
          install.packages("remotes", repos = "https://cloud.r-project.org")
          remotes::install_github("rladies/meetupr")
          remotes::install_cran(c("dplyr", "here", "purrr", "jsonlite"))
          remotes::install_cran(c("tidyr", "lubridate"))
          remotes::install_cran(c("cyphr", "sodium"))
        shell: Rscript {0}
              
      - name: Populate untranslated pages
        run: Rscript scripts/missing_translations.R
        
      - name: Site data - Get directory data
        uses: actions/checkout@v2
        with:
          repository: rladies/directory
          token: ${{ secrets.directory_PAT_mo }}
          path: directory
      
      - name: Site data - Cleanup directory data
        run: |
          rm directory/data/[1-9]_* # remove double entries. can be deleted after manual clean
          mv directory/data data/directory
          rm -rf directory
        
      - name: Meetup authentication
        env: 
          MEETUPR_PWD: ${{ secrets.MEETUPR_PWD }}
        run: Rscript scripts/meetup_auth.R
        
      - name: Site data - Update chapter data
        env: 
          MEETUPR_PWD: ${{ secrets.MEETUPR_PWD }}
        run: Rscript scripts/get_chapters.R
        
      - name: Site data - Update event data
        env: 
          MEETUPR_PWD: ${{ secrets.MEETUPR_PWD }}
        run: Rscript scripts/get_events.R

      - name: Build
        env: 
          DIRECTORY_PAT: ${{ secrets.DIRECTORY_PAT }}
        run: hugo --buildFuture 

      - name: Install netlify
        run: npm install netlify-cli -g
        
      - name: Deploy to Netlify production
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod
          
      - name: Deploy Netlify preview
        if: github.event_name == 'pull_request'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy
