name: Validate directory jsons

on:
  push:
    paths:
      - '**.json'
  pull_request:
    paths:
      - '**.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  jsons:
    name: Check modified jsons
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: check_files
        run: |
          jsons=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep json$ | xargs)
          if [[ "${jsons[*]}" = *[![:space:]]* ]]; then 
            echo ${jsons}
            echo "{run_validation}={true}" >> $GITHUB_ENV
          else
            echo "No jsons commited/changed"
            echo "{run_validation}={false}" >> $GITHUB_ENV
          fi
          
      - name: Setup R
        if: env.run_validation == 'true'
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R-packages
        if: env.run_validation == 'true'
        run: install.packages(c("here", "jsonvalidate"), Ncpus = 2)
        shell: Rscript {0}
      
      - name: Validate jsons
        if: env.run_validation == 'true'
        run: Rscript scripts/validate_jsons.R
          
          